(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x600_duhovoy_shkaf_atlas_", frames: [[0,624,600,337],[602,0,363,343],[602,883,274,92],[602,737,266,144],[602,549,256,186],[602,345,241,202],[0,0,600,622]]}
];


// symbols:



(lib.Bitmap10 = function() {
	this.spriteSheet = ss["300x600_duhovoy_shkaf_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap9 = function() {
	this.spriteSheet = ss["300x600_duhovoy_shkaf_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.Layer11 = function() {
	this.spriteSheet = ss["300x600_duhovoy_shkaf_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.Layer21111 = function() {
	this.spriteSheet = ss["300x600_duhovoy_shkaf_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.Layer31 = function() {
	this.spriteSheet = ss["300x600_duhovoy_shkaf_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.Layer4 = function() {
	this.spriteSheet = ss["300x600_duhovoy_shkaf_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.oven = function() {
	this.spriteSheet = ss["300x600_duhovoy_shkaf_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAAGIgCgBQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAABIgBAEIgDABg");
	this.shape.setTransform(222.3,37.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOATQgEgFAAgKIAAgXIABgDQAAAAAAAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAXQAAAGADADQACADAFAAQAGAAADgDQACgDAAgGIAAgXQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAABQAAAAABAAIAAADIAAAXQAAAKgEAFQgGAFgJAAQgIAAgGgFg");
	this.shape_1.setTransform(218.7,35.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMAXIgCgDIAAgmIACgDIADgBIADABIABADIAAAFQACgEADgDQAEgDAFAAIAEABQABABAAAAQAAAAAAABQABAAAAAAQAAABAAAAIgBAEIgDABIgDgBIgDgBIgFACIgDAGQgCADAAAEIAAAVIgBADIgDABIgDgBg");
	this.shape_2.setTransform(214.5,35.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAAGIgCgBQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIAAAAQABAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAABIgBAEIgEABg");
	this.shape_3.setTransform(211.4,37.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AADAdIgDgBIgDgEIgCgGIAAgbIgFAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIACgBIAFAAIAAgIIACgDIADgBIACABQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAAAIIAIAAIACABQABAAAAAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAIgCABIgIAAIAAAaIABAEIADABIACgBIACAAIACABIAAADQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQgCABgDAAIgDAAg");
	this.shape_4.setTransform(208.8,34.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgXQAAgGgDgDQgCgDgFAAQgDAAgDACIgFAFQgBADAAAEIAAAVIgCADQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAgBAAIgBgDIAAgmIABgDQABAAAAAAQAAgBABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIACADIAAADQACgDAEgDQAEgCAEAAQAIAAAEAFQAEAFAAAJIAAAYQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAg");
	this.shape_5.setTransform(204.5,35.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgCAeIgBgDIAAgmIABgCQAAgBABAAQAAAAAAgBQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIACACIAAAmIgCADQAAAAgBABQAAAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQgBgBAAAAgAgCgWQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgCQAAAAAAAAQAAgBAAAAQABgBAAAAQAAAAABAAIACgBIADABQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAAAIAAACQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgDABIgCgBg");
	this.shape_6.setTransform(200.8,34.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_7.setTransform(196.9,35.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUAgIgCgDIAAg4IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAADIAEgEIAFgDIAFgBQAGAAAFADQAFADADAFQADAGAAAIQAAAGgDAFQgDAFgFADQgEAEgHAAQgEgBgEgCQgEgCgCgCIAAAUIgBADIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAFQAAAEABADQACADAEADQADACADAAQAEAAAEgDQADgCACgDQACgDAAgEQAAgFgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_8.setTransform(191.4,36.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AADAdIgDgBIgDgEIgCgGIAAgbIgFAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIACgBIAFAAIAAgIIACgDIADgBIACABQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAAAIIAIAAIACABQABAAAAAAQAAABAAAAQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAAAABQAAAAgBAAIgCABIgIAAIAAAaIABAEIADABIACgBIACAAIACABIAAADQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBABQgCABgDAAIgDAAg");
	this.shape_9.setTransform(186.9,34.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_10.setTransform(182.5,35.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAMAgQAAAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgYIgBgFQgBgDgCgBQgCgCgEAAQgDAAgCACQgDABgBADIgCAFIAAAYQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAIgDABIgCgBIgBgDIAAg5IABgDIACgBIADABIACADIAAAXIADgEIAGgEIAFgBQAGAAADADQAEADACAEIAAAJIAAAYIAAADIgDABIgEgBg");
	this.shape_11.setTransform(177.2,34.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAAAGIgCgBQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAAAAAgBIAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIAAAAQABAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAABIgBAEIgEABg");
	this.shape_12.setTransform(173.5,37.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AALAXIgCgCIgJgXIgIAXIgBACIgCABIgDgBIgCgCIgOglIAAgBIAAgBIABgDQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIACABQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIALAdIAIgVIACgCIABgBIADABIABACIAJAVIAKgdIACgCIACgBQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIABADIAAABIAAABIgOAlIgBACIgDABIgCgBg");
	this.shape_13.setTransform(169.1,35.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AALAXIgCgCIgJgXIgIAXIgBACIgCABIgDgBIgCgCIgOglIAAgBIAAgBIABgDQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIACABQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIALAdIAIgVIACgCIABgBIADABIABACIAJAVIAKgdIACgCIACgBQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIABADIAAABIAAABIgOAlIgBACIgDABIgCgBg");
	this.shape_14.setTransform(162.4,35.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AALAXIgCgCIgJgXIgIAXIgBACIgCABIgDgBIgCgCIgOglIAAgBIAAgBIABgDQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIACABQABAAAAABQAAAAAAAAQABAAAAABQAAAAAAAAIALAdIAIgVIACgCIABgBIADABIABACIAJAVIAKgdIACgCIACgBQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIABADIAAABIAAABIgOAlIgBACIgDABIgCgBg");
	this.shape_15.setTransform(155.7,35.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgKAWQgFgEgDgFQgDgFAAgHQAAgHADgGQADgGAFgCQAFgDAFgBQAGABAFACQAFADADAGQADAFAAAGIgBACIgDABIgfAAQAAAFADADQACADADACQADACAEAAQAEAAADgCIAEgDIACAAIABgBQABAAAAAAQAAAAABABQAAAAAAAAQAAAAABABIABACIgBACIgBACQgDACgEACQgEACgFAAQgGAAgGgDgAgFgOQgDABgCACQgCADgBAEIAaAAIAAgBQAAgDgCgCIgFgEQgDgCgDAAQgCAAgDACg");
	this.shape_16.setTransform(147.6,35.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgCAWIgBgDIAAgiIgNAAIgDgBIgBgDIABgCQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIAhAAQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACACIgCADIgCABIgNAAIAAAiQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBg");
	this.shape_17.setTransform(142.8,35.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AANAeIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIABADIAAAbIAYgeIABgBIACgBQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAAmIgBADIgDABIgDgBgAgIgTQgEgDgBgEQAAgBAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIACgBIADABIACACIACADIAEABIADgBQABAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAIACgCIACgBIACABQABAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQgCAEgDADQgEACgEAAQgFAAgDgCg");
	this.shape_18.setTransform(137.9,34.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgLAVQgFgDgDgFQgDgGAAgHQAAgGADgGQADgFAFgDQAFgDAGgBQAEABAEACQAEACACAEIAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABIABADIAAAlIgBAEIgDABIgDgBQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgDQgCAEgEACQgEADgFAAQgGAAgEgEgAgGgNQgEACgBADQgCAEAAAEQAAAFACAEQABADAEADQADACADAAQAFAAADgCQADgDACgDQACgEAAgFQAAgEgCgDQgCgEgDgCQgDgDgFAAQgDAAgDADg");
	this.shape_19.setTransform(132.2,35.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgJAVQgEgDgEgFQgCgGAAgHQAAgGADgGQADgFAFgDQAFgDAHgBQAEAAAEACIAFACQABABABAAQAAABAAAAQABABAAAAQAAABAAAAIgBADIgDABIgCAAIgBgBIgCgBIgDgBIgDgBQgFAAgDADQgEACgCAEQgCADAAAEQAAAFACAEQACADAEADQADACAEAAIAEgBIAEgBIACgBIACgBIADABIABADQAAAAAAABQAAAAgBABQAAAAAAAAQAAABgBAAQgCACgEABQgEACgFAAQgGAAgGgEg");
	this.shape_20.setTransform(127.3,35.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgLAVQgFgDgDgFQgDgGAAgHQAAgGADgGQADgFAFgDQAFgDAGgBQAEABAEACQAEACACAEIAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAlIgBAEIgDABIgDgBQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgDQgCAEgEACQgEADgFAAQgGAAgEgEgAgGgNQgEACgBADQgCAEAAAEQAAAFACAEQABADAEADQADACADAAQAFAAADgCQADgDACgDQACgEAAgFQAAgEgCgDQgCgEgDgCQgDgDgFAAQgDAAgDADg");
	this.shape_21.setTransform(119.7,35.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AANAWIgBgDIAAgPIgWAAIAAAPIgCADQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBIgBgDIAAglIABgDQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACADIAAAPIAWAAIAAgPIABgDIADgCQAAAAABAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAlQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAAAAAQgBABAAAAQgBAAAAAAIgDgCg");
	this.shape_22.setTransform(114.3,35.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABIABADIAAAbIAYgeIABgBIACgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAmIgBADIgDABIgDgBg");
	this.shape_23.setTransform(106.7,35.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgCAWIgBgDIAAgiIgNAAIgDgBIgBgDIABgCQABgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAIAhAAQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACACIgCADIgCABIgNAAIAAAiQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBg");
	this.shape_24.setTransform(101.8,35.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgJAVQgEgDgEgFQgCgGAAgHQAAgGADgGQADgFAFgDQAGgDAFgBQAFAAAEACIAGACQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAIgBADIgCABIgCAAIgDgBIgBgBIgDgBIgDgBQgFAAgDADQgDACgDAEQgBADAAAEQAAAFABAEQADADADADQADACAEAAIAEgBIADgBIADgBIADgBIACABIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQgDACgEABQgEACgEAAQgGAAgGgEg");
	this.shape_25.setTransform(97.3,35.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_26.setTransform(92.1,35.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AANAWIgBgDIAAgPIgWAAIAAAPIgCADQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAgBgBIgBgDIAAglIABgDQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACADIAAAPIAWAAIAAgPIABgDIADgCQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAlQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgDgCg");
	this.shape_27.setTransform(86.6,35.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgQAbQgGgHAAgNQAAgOAEgJQAEgJAKgCIAEgCIAGgBIAEAAIADgCIACgBIACAAIACABIACACIgCAFIgFACIgGABIgFABIgFABIgGADQgCACgBAEIgCAIQACgEAEgCQAEgCAEAAQAGAAAGACQAEADADAGQADAEAAAHQAAAHgDAFQgDAFgFADQgGADgGAAQgKAAgGgHgAgHgBQgDABgBADQgCADAAAEQAAAIADAEQAEAEAGAAQAHAAADgEQAFgEAAgHQAAgFgCgDQgCgDgEgCQgDgBgEAAQgDAAgEACg");
	this.shape_28.setTransform(81.3,34.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_29.setTransform(75.6,35.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgUAgIgCgDIAAg4IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAADIAEgEIAFgDIAFgBQAGAAAFADQAFADADAFQADAGAAAIQAAAGgDAFQgDAFgFADQgEAEgHAAQgEgBgEgCQgEgCgCgCIAAAUIgBADIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAFQAAAEABADQACADAEADQADACADAAQAEAAAEgDQADgCACgDQACgDAAgEQAAgFgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_30.setTransform(70.2,36.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AASAdQAAgBgBAAQAAAAAAAAQAAgBAAAAQgBgBAAAAIAAgIIgfAAIAAAIQAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAABIgDABIgDgBIgBgDIAAgMIABgDIADgBIABAAIACgDIACgFIABgIIAAgOIAAgFQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAYAAIAEABIABADIAAAjIACAAIADABIABADIAAAMIgBADIgDABIgDgBgAgFgUIgBAPIgBAJIgDAGIAUAAIAAgfIgPAAg");
	this.shape_31.setTransform(64.5,35.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_32.setTransform(59,35.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AARAfIgBgEIAAgxIgfAAIAAAxIgBAEIgDABIgDgBQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIAAg1IABgDIAEgBIAnAAIAEABIABACIAAA2QAAABAAAAQAAAAgBABQAAAAAAABQAAAAgBABIgDABIgDgBg");
	this.shape_33.setTransform(53,34.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAAAFIgCAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIAAAAQABAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAABIgBAEIgEAAg");
	this.shape_34.setTransform(228.8,24.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgOAXIgBgDIAAgnIABgCQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAABAAIAXAAIADABIABADQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgDABIgSAAIAAAjIgCADIgDABIgDgBg");
	this.shape_35.setTransform(226,22.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgMAcQgFgEgCgHQgDgIAAgJQAAgIADgIQACgHAFgEQAFgEAHAAQAIAAAEAEQAGAEACAHQADAIAAAIQAAAJgDAIQgCAHgGAEQgEAEgIAAQgHAAgFgEgAgJgQQgEAFAAALQAAAMAEAFQAEAHAFAAQAGAAAEgHQADgFAAgMQAAgLgDgFQgEgHgGAAQgFAAgEAHg");
	this.shape_36.setTransform(220.9,22.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgPAgIgDgBIgBgDIABgBIAAgCIATgWIAGgHQADgEAAgEQAAgFgDgDQgEgDgDAAQgEAAgDACQgDACgCADIgBACIgCAAIgDgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIABgDIABgDQADgDAFgCQAEgDAFAAQAFAAAEADQAFACACAEQACAFAAAFQABAFgDAGQgDAFgGAFIgMAPIAVAAIADABIABADQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAIgDABg");
	this.shape_37.setTransform(215.7,22);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgMAcQgFgEgDgHQgCgIAAgJQAAgIACgIQADgHAFgEQAFgEAHAAQAHAAAGAEQAEAEAEAHQACAIAAAIQAAAJgCAIQgEAHgEAEQgGAEgHAAQgHAAgFgEgAgKgQQgDAFAAALQAAAMADAFQAFAHAFAAQAGAAAEgHQADgFABgMQgBgLgDgFQgEgHgGAAQgFAAgFAHg");
	this.shape_38.setTransform(210.5,22.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgOAgIgDgBIgCgDIAAgBIACgCIATgWIAFgHQADgEAAgEQAAgFgEgDQgCgDgFAAQgDAAgDACQgDACgCADIgCACIgBAAIgDgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIABgDIACgDQADgDAFgCQAEgDAFAAQAFAAAFADQAEACACAEQADAFAAAFQAAAFgDAGQgDAFgGAFIgMAPIAVAAIADABIACADQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAIgDABg");
	this.shape_39.setTransform(205.3,22);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgLAVQgFgDgDgFQgDgGAAgHQAAgGADgGQADgFAFgDQAFgDAGgBQAEABAEACQAEACACAEIAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAABABIABADIAAAlIgBAEIgDABIgDgBQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgDQgCAEgEACQgEADgFAAQgGAAgEgEgAgGgNQgEACgBADQgCAEAAAEQAAAFACAEQABADAEADQADACADAAQAFAAADgCQADgDACgDQACgEAAgFQAAgEgCgDQgCgEgDgCQgDgDgFAAQgDAAgDADg");
	this.shape_40.setTransform(197.7,22.8);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgCAWIgBgDIAAgiIgNAAIgDgBIgBgDIABgCQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAIAhAAQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACACIgCADIgCABIgNAAIAAAiQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAAAAAQgBABAAAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBg");
	this.shape_41.setTransform(192.9,22.8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgUAgIgCgEIAAg3IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAAAAAQABAAAAAAQABABAAAAIABADIAAACIAEgDIAFgDIAFgBQAGAAAFADQAFADADAFQADAGAAAIQAAAGgDAFQgDAFgFADQgEAEgHAAQgEgBgEgCQgEgCgCgCIAAATIgBAEIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAFQAAAEABADQACAEAEACQADACADAAQAEAAAEgDQADgBACgEQACgDAAgEQAAgFgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_42.setTransform(188,23.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgLAVQgFgDgDgFQgDgGAAgHQAAgGADgGQADgFAFgDQAFgDAGgBQAEABAEACQAEACACAEIAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAlIgBAEIgDABIgDgBQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgDQgCAEgEACQgEADgFAAQgGAAgEgEgAgGgNQgEACgBADQgCAEAAAEQAAAFACAEQABADAEADQADACADAAQAFAAADgCQADgDACgDQACgEAAgFQAAgEgCgDQgCgEgDgCQgDgDgFAAQgDAAgDADg");
	this.shape_43.setTransform(182.1,22.8);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAQAWIgBgDIAAgaIgMARIgBABIgCAAIgBAAIgCgCIgLgQIAAAbIgBADIgEABIgDgBIgBgDIAAgmIABgDQABgBAAAAQAAAAABAAQAAgBABAAQAAAAAAAAIADABIACACIAPAVIAOgVIACgCIADgBQAAAAAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIAAAlQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAIgDgCg");
	this.shape_44.setTransform(176.5,22.8);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgMAcQgFgEgDgHQgCgIAAgJQAAgIACgIQADgHAFgEQAGgEAGAAQAIAAAEAEQAFAEAEAHQACAIAAAIQAAAJgCAIQgEAHgFAEQgEAEgIAAQgGAAgGgEgAgKgQQgDAFAAALQAAAMADAFQAFAHAFAAQAHAAADgHQADgFAAgMQAAgLgDgFQgDgHgHAAQgFAAgFAHg");
	this.shape_45.setTransform(168.4,22.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgJAfIgGgDIgCgCIgBgBIABgEIADgBIACAAIACABIAEADIAFABQACAAADgCQADgCACgDIACgHIgCgGQgCgEgCgBIgFAAIgEAAIgDAAQgBAAAAAAQgBAAAAAAQAAAAAAAAQgBAAAAAAIgBgDIABgCIABgBIAOgRIgUAAIgDgBIgBgDIABgDIADgBIAcAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAABIgBABIgOAQQAFAAAEADQAEADACACQADAFAAAFQAAAHgDAFQgDAEgGADQgFADgGAAIgGgBg");
	this.shape_46.setTransform(163.2,22.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_47.setTransform(155.9,22.8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AANAXIgCgDIAAgjIgVAAIAAAjIgBADIgDABIgDgBIgCgDIAAgnIACgCQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIAfAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABIABACIAAAnIgBADIgEABIgCgBg");
	this.shape_48.setTransform(150.4,22.8);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AAAAFIgDAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAABIgBAEIgDAAg");
	this.shape_49.setTransform(144.6,24.7);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgOAXIgBgDIAAgnIABgCQABgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAXAAIADABIABADQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAIgDABIgSAAIAAAjIgCADIgDABIgDgBg");
	this.shape_50.setTransform(141.8,22.8);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgMAcQgFgEgDgHQgCgIAAgJQAAgIACgIQADgHAFgEQAFgEAHAAQAHAAAGAEQAEAEAEAHQACAIAAAIQAAAJgCAIQgEAHgEAEQgGAEgHAAQgHAAgFgEgAgKgQQgDAFAAALQAAAMADAFQAFAHAFAAQAGAAAEgHQADgFABgMQgBgLgDgFQgEgHgGAAQgFAAgFAHg");
	this.shape_51.setTransform(136.7,22.1);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgOAgIgDgBIgCgDIAAgBIACgCIATgWIAFgHQADgEAAgEQAAgFgEgDQgCgDgFAAQgDAAgDACQgDACgCADIgBACIgCAAIgDgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIABgDIACgDQADgDAFgCQAEgDAFAAQAFAAAFADQAEACACAEQADAFAAAFQAAAFgDAGQgDAFgGAFIgMAPIAVAAIADABIACADQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAIgDABg");
	this.shape_52.setTransform(131.5,22);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgMAcQgFgEgCgHQgDgIAAgJQAAgIADgIQACgHAFgEQAGgEAGAAQAIAAAEAEQAGAEACAHQADAIAAAIQAAAJgDAIQgCAHgGAEQgEAEgIAAQgGAAgGgEgAgJgQQgEAFAAALQAAAMAEAFQAEAHAFAAQAHAAADgHQAEgFgBgMQABgLgEgFQgDgHgHAAQgFAAgEAHg");
	this.shape_53.setTransform(126.3,22.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgPAgIgCgBIgCgDIABgBIABgCIASgWIAHgHQACgEAAgEQAAgFgDgDQgDgDgEAAQgEAAgDACQgDACgCADIgCACIgBAAIgDgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIABgDIABgDQADgDAFgCQAEgDAFAAQAFAAAEADQAFACADAEQABAFAAAFQABAFgDAGQgDAFgFAFIgNAPIAWAAIACABIABADQAAABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAIgCABg");
	this.shape_54.setTransform(121.1,22);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgLAVQgFgDgDgFQgDgGAAgHQAAgGADgGQADgFAFgDQAFgDAGgBQAEABAEACQAEACACAEIAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABIABADIAAAlIgBAEIgDABIgDgBQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgDQgCAEgEACQgEADgFAAQgGAAgEgEgAgGgNQgEACgBADQgCAEAAAEQAAAFACAEQABADAEADQADACADAAQAFAAADgCQADgDACgDQACgEAAgFQAAgEgCgDQgCgEgDgCQgDgDgFAAQgDAAgDADg");
	this.shape_55.setTransform(113.5,22.8);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgCAWIgBgDIAAgiIgNAAIgDgBIgBgDIABgCQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAhAAQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACACIgCADIgCABIgNAAIAAAiQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABAAAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBg");
	this.shape_56.setTransform(108.7,22.8);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgUAgIgCgEIAAg3IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAABAAQAAAAAAAAQAAABABAAIABADIAAACIAEgDIAFgDIAFgBQAGAAAFADQAFADADAFQADAGAAAIQAAAGgDAFQgDAFgFADQgEAEgHAAQgEgBgEgCQgEgCgCgCIAAATIgBAEIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAFQAAAEABADQACAEAEACQADACADAAQAEAAAEgDQADgBACgEQACgDAAgEQAAgFgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_57.setTransform(103.8,23.7);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgLAVQgFgDgDgFQgDgGAAgHQAAgGADgGQADgFAFgDQAFgDAGgBQAEABAEACQAEACACAEIAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABIABADIAAAlIgBAEIgDABIgDgBQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgDQgCAEgEACQgEADgFAAQgGAAgEgEgAgGgNQgEACgBADQgCAEAAAEQAAAFACAEQABADAEADQADACADAAQAFAAADgCQADgDACgDQACgEAAgFQAAgEgCgDQgCgEgDgCQgDgDgFAAQgDAAgDADg");
	this.shape_58.setTransform(97.9,22.8);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AAQAWIgBgDIAAgaIgNARIgBABIgBAAIgBAAIgBgCIgNgQIAAAbIgBADIgCABIgDgBIgCgDIAAgmIACgDQAAgBAAAAQAAAAABAAQAAgBABAAQAAAAABAAIACABIACACIAOAVIAQgVIABgCIACgBQABAAAAAAQABAAAAABQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABQABAAAAABIAAAlQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgDgCg");
	this.shape_59.setTransform(92.3,22.8);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgLAeIgBgCIAAgBIABgBIAVgxIgZAAIgDgBIgCgDQAAAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAIADgBIAfAAIADABIABADIAAABIAAABIgYA2IgBACIgCABQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBgBg");
	this.shape_60.setTransform(84.8,22.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AAEAfQAAgBgBAAQAAgBAAAAQAAgBAAAAQgBgBAAAAIAAguIgGAFIgCABIgBAAIgCgBIgCgEIABgCIABgCIAOgIIABgBIACAAIADACIABADIAAA1QAAAAAAABQAAAAAAABQgBAAAAABQAAAAgBABIgDAAIgDAAg");
	this.shape_61.setTransform(80.7,22.1);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgJAVQgFgDgDgFQgCgGAAgHQAAgGADgGQADgFAFgDQAFgDAHgBQAEAAAEACIAFACQABABABAAQAAABAAAAQABABAAAAQAAABAAAAIgBADIgCABIgCAAIgCgBIgCgBIgDgBIgDgBQgFAAgDADQgEACgCAEQgBADAAAEQAAAFABAEQACADAEADQADACAEAAIAEgBIADgBIADgBIADgBIACABIABADQAAAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQgDACgEABQgEACgEAAQgGAAgGgEg");
	this.shape_62.setTransform(74.9,22.8);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAbIAYgeIABgBIACgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAmIgBADIgDABIgDgBg");
	this.shape_63.setTransform(67.5,22.8);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABIABADIAAAbIAYgeIABgBIACgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAmIgBADIgDABIgDgBg");
	this.shape_64.setTransform(62,22.8);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AAQAdQAAgBgBAAQAAAAAAAAQAAgBAAAAQgBAAAAgBIAAgIIggAAIgDgBIgBgDIAAgnIABgDIADgBIAEABIABADIAAAjIAUAAIAAgjQAAAAABgBQAAAAAAAAQAAgBAAAAQABgBAAAAIADgBIADABIABADIAAAjIADAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIAAAMIgBADIgDABIgDgBg");
	this.shape_65.setTransform(56.7,23.4);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AAOAXIgCgBQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgEgGQgBgFgDgCQgCgCgEAAIgFAAIAAAPIgCADQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBIgBgDIAAglIABgDQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACADIAAAPIAFAAQAEAAACgCQADgCABgEIADgHIADgDIADgBIACgBIACABIABADIAAACIgBABIgDADIgCAEIgEAGIgFADQADABACADIAEAGIADAEIACADIACABIAAACQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgCgBg");
	this.shape_66.setTransform(51.5,22.8);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgLAVQgFgDgDgFQgDgGAAgHQAAgGADgGQADgFAFgDQAFgDAGgBQAEABAEACQAEACACAEIAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAlIgBAEIgDABIgDgBQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgDQgCAEgEACQgEADgFAAQgGAAgEgEgAgGgNQgEACgBADQgCAEAAAEQAAAFACAEQABADAEADQADACADAAQAFAAADgCQADgDACgDQACgEAAgFQAAgEgCgDQgCgEgDgCQgDgDgFAAQgDAAgDADg");
	this.shape_67.setTransform(45.9,22.8);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AAOAWQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgNIgJAAIgDABIgDACIgCAFIgDAGIgEADIgCAAIgCABIgDgBIgBgDIABgCIABgBIADgCIACgEIADgEQAAgBAAAAQABgBAAAAQABAAAAgBQABAAAAAAQgFgDgCgCQgCgDAAgFQAAgGAEgEQAEgDAHgBIASAAIADACIABADIAAAlIgBADQgBABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBgAgFgNQgDACAAADQAAAEADACQACACADAAIAMAAIAAgPIgMAAQgDAAgCACg");
	this.shape_68.setTransform(256.6,10.3);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAbIAYgeIABgBIACgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAmIgBADIgDABIgDgBg");
	this.shape_69.setTransform(251.5,10.3);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AANAWIgBgDIAAgPIgWAAIAAAPIgCADQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAAAgBgBIgBgDIAAglIABgDQABgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACADIAAAPIAWAAIAAgPIABgDIADgCQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAlQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgDgCg");
	this.shape_70.setTransform(246.1,10.3);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AgKAWQgFgEgDgFQgDgFAAgHQAAgHADgGQADgGAFgCQAFgDAFgBQAGABAFACQAFADADAGQADAFAAAGIgBACIgDABIgfAAQAAAFADADQACADADACQADACAEAAQAEAAADgCIAEgDIACAAIABgBQABAAAAAAQAAAAABABQAAAAAAAAQABAAAAABIABACIgBACIgBACQgDACgEACQgEACgFAAQgGAAgGgDgAgFgOQgDABgCACQgCADgBAEIAaAAIAAgBQAAgDgCgCIgFgEQgDgCgDAAQgCAAgDACg");
	this.shape_71.setTransform(240.9,10.3);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AASAdQAAgBgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIAAgIIggAAIAAAIQAAABAAAAQAAAAAAABQAAAAAAAAQgBAAAAABIgDABIgDgBIgCgDIAAgMIACgDIADgBIABAAIACgDIACgFIABgIIAAgOIAAgFQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAZAAIACABIABADIAAAjIADAAIADABIACADIAAAMIgCADIgDABIgDgBgAgFgUIgBAPIgCAJIgCAGIAUAAIAAgfIgPAAg");
	this.shape_72.setTransform(235.5,10.9);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AgKAWQgFgEgDgFQgDgFAAgHQAAgHADgGQADgGAFgCQAFgDAFgBQAGABAFACQAFADADAGQADAFAAAGIgBACIgDABIgfAAQAAAFADADQACADADACQADACAEAAQAEAAADgCIAEgDIACAAIABgBQABAAAAAAQAAAAABABQAAAAAAAAQABAAAAABIABACIgBACIgBACQgDACgEACQgEACgFAAQgGAAgGgDgAgFgOQgDABgCACQgCADgBAEIAaAAIAAgBQAAgDgCgCIgFgEQgDgCgDAAQgCAAgDACg");
	this.shape_73.setTransform(230.3,10.3);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AgOAYIgDgBIgCgDIAAgnIACgCQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAIARAAQAHABAEADQADADAAAFQAAADgBADQgCADgDACQAEAAACADQACACABAGQgBAFgCACQgCADgEACIgHABgAgKAQIAOAAQADAAACgBQACgCAAgDQAAgEgCgBQgDgCgDAAIgNAAgAgKgDIANAAQAAAAABAAQABAAAAgBQABAAAAAAQABAAAAgBQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgNAAg");
	this.shape_74.setTransform(225.3,10.3);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_75.setTransform(219.9,10.3);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AgUAgIgCgEIAAg3IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAABAAQAAAAAAAAQAAABABAAIABADIAAACIAEgDIAFgDIAFgBQAGAAAFADQAFADADAGQADAFAAAHQAAAHgDAFQgDAFgFADQgEAEgHAAQgEAAgEgDQgEgCgCgCIAAATIgBAEIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAEQAAAFABADQACAEAEACQADACADAAQAEAAAEgCQADgDACgDQACgDAAgFQAAgEgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_76.setTransform(214.5,11.2);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AANAXIgCgDIAAgjIgVAAIAAAjIgBADIgDABIgDgBIgCgDIAAgnIACgCQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIAfAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABIABACIAAAnIgBADIgEABIgCgBg");
	this.shape_77.setTransform(208.9,10.3);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AAOAXIgCgBQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgEgGQgBgFgDgCQgCgCgEAAIgFAAIAAAPIgCADQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAgBgBIgBgDIAAglIABgDQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACADIAAAPIAFAAQAEAAACgCQADgCABgEIADgHIADgDIADgBIACgBIACABIABADIAAACIgBABIgDADIgCAEIgEAGIgFADQADABACADIAEAGIADAEIACADIACABIAAACQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgCgBg");
	this.shape_78.setTransform(201.7,10.3);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_79.setTransform(196.3,10.3);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgUAgIgCgEIAAg3IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIABADIAAACIAEgDIAFgDIAFgBQAGAAAFADQAFADADAGQADAFAAAHQAAAHgDAFQgDAFgFADQgEAEgHAAQgEAAgEgDQgEgCgCgCIAAATIgBAEIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAEQAAAFABADQACAEAEACQADACADAAQAEAAAEgCQADgDACgDQACgDAAgFQAAgEgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_80.setTransform(190.8,11.2);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AgJAcQgHgDgEgIQgEgHAAgKQAAgJAEgHQAEgHAHgEQAHgEAJAAIAIABIAIADIACACIAAACIgBADIgDABIgBAAIgBgBIgGgCIgGgBQgHAAgFADQgFADgCAFQgDAGAAAGQAAAIADAFQADAFAFADQAEADAHAAIAGgBIAGgDIABAAIABAAIADABIABADIAAACIgCACIgIADQgEABgEAAQgIAAgIgEg");
	this.shape_81.setTransform(185.1,9.6);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AAAAFIgDgBQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAAAAAIABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAABIgBADIgDABg");
	this.shape_82.setTransform(178.9,12.2);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFFFF").s().p("AgCAgQAAAAgBAAQAAAAAAgBQAAAAAAgBQgBAAAAAAIAAgDQgHAAgHgEQgGgDgEgHQgDgFAAgIQAAgHADgGQAEgGAGgEQAHgDAHAAIAAgDQAAAAABAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABQAAAAAAAAIAAADQAJAAAGADQAGAEAEAGQADAGAAAHQAAAIgDAFQgEAHgGADQgGAEgJAAIAAADQAAAAAAAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAAAAAQAAAAAAAAQAAAAgBAAQAAgBAAAAQgBAAAAgBgAAEATQAGAAAEgDQAEgCADgEQACgFAAgFQAAgFgCgEQgDgEgEgCQgEgDgGAAgAgNgPQgEACgDAFQgCAEAAAEQAAAFACAFQADAEAEACQAEADAFAAIAAglQgFABgEACg");
	this.shape_83.setTransform(174.3,9.6);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("AgTAeQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAg1IABgEIAEgBIASAAQAGABAEACQAFACACAFQADAEAAAFQAAAHgDADQgCAEgFACQgEADgGAAIgOAAIAAAUIgBADQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAgBAAAAgAgMAAIAPAAQAFAAACgDQADgDAAgGQAAgEgDgEQgCgCgFgBIgPAAg");
	this.shape_84.setTransform(168.2,9.6);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABIABADIAAAbIAYgeIABgBIACgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAmIgBADIgDABIgDgBg");
	this.shape_85.setTransform(160.2,10.3);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAbIAYgeIABgBIACgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAmIgBADIgDABIgDgBg");
	this.shape_86.setTransform(154.8,10.3);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("AgUAgIgCgEIAAg3IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAACIAEgDIAFgDIAFgBQAGAAAFADQAFADADAGQADAFAAAHQAAAHgDAFQgDAFgFADQgEAEgHAAQgEAAgEgDQgEgCgCgCIAAATIgBAEIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAEQAAAFABADQACAEAEACQADACADAAQAEAAAEgCQADgDACgDQACgDAAgFQAAgEgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_87.setTransform(149.4,11.2);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_88.setTransform(143.7,10.3);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#FFFFFF").s().p("AgCAWIgBgDIAAgiIgNAAIgDgBIgBgDIABgCQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAAAIAhAAQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACACIgCADIgCABIgNAAIAAAiQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBg");
	this.shape_89.setTransform(138.7,10.3);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABIABADIAAAbIAYgeIABgBIACgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAmIgBADIgDABIgDgBg");
	this.shape_90.setTransform(133.8,10.3);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#FFFFFF").s().p("AgUAgIgCgEIAAg3IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIABADIAAACIAEgDIAFgDIAFgBQAGAAAFADQAFADADAGQADAFAAAHQAAAHgDAFQgDAFgFADQgEAEgHAAQgEAAgEgDQgEgCgCgCIAAATIgBAEIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAEQAAAFABADQACAEAEACQADACADAAQAEAAAEgCQADgDACgDQACgDAAgFQAAgEgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_91.setTransform(128.4,11.2);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFFF").s().p("AgUAgIgCgEIAAg3IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABABAAIABADIAAACIAEgDIAFgDIAFgBQAGAAAFADQAFADADAGQADAFAAAHQAAAHgDAFQgDAFgFADQgEAEgHAAQgEAAgEgDQgEgCgCgCIAAATIgBAEIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAEQAAAFABADQACAEAEACQADACADAAQAEAAAEgCQADgDACgDQACgDAAgFQAAgEgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_92.setTransform(122.8,11.2);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FFFFFF").s().p("AgKAWQgFgEgDgFQgDgFAAgHQAAgHADgGQADgGAFgCQAFgDAFgBQAGABAFACQAFADADAGQADAFAAAGIgBACIgDABIgfAAQAAAFADADQACADADACQADACAEAAQAEAAADgCIAEgDIACAAIABgBQABAAAAAAQAAAAABABQAAAAAAAAQAAAAABABIABACIgBACIgBACQgDACgEACQgEACgFAAQgGAAgGgDgAgFgOQgDABgCACQgCADgBAEIAaAAIAAgBQAAgDgCgCIgFgEQgDgCgDAAQgCAAgDACg");
	this.shape_93.setTransform(117.3,10.3);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FFFFFF").s().p("AgCAWIgBgDIAAgiIgNAAIgDgBIgBgDIABgCQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAAAIAhAAQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACACIgCADIgCABIgNAAIAAAiQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBg");
	this.shape_94.setTransform(112.5,10.3);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FFFFFF").s().p("AgLAVQgFgDgDgFQgDgGAAgHQAAgGADgGQADgFAFgDQAFgDAGgBQAEABAEACQAEACACAEIAAgDQAAgBAAAAQAAgBABAAQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABIABADIAAAlIgBAEIgDABIgDgBQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAgDQgCAEgEACQgEADgFAAQgGAAgEgEgAgGgNQgEACgBADQgCAEAAAEQAAAFACAEQABADAEADQADACADAAQAFAAADgCQADgDACgDQACgEAAgFQAAgEgCgDQgCgEgDgCQgDgDgFAAQgDAAgDADg");
	this.shape_95.setTransform(105.1,10.3);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FFFFFF").s().p("AANAWIgBgDIAAgPIgWAAIAAAPIgCADQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAgBgBIgBgDIAAglIABgDQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACADIAAAPIAWAAIAAgPIABgDIADgCQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAlQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgDgCg");
	this.shape_96.setTransform(99.8,10.3);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#FFFFFF").s().p("AAOAWQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgNIgJAAIgDABIgDACIgCAFIgDAGIgEADIgCAAIgCABIgDgBIgBgDIABgCIABgBIADgCIACgEIADgEQAAgBAAAAQABgBAAAAQABAAAAgBQABAAAAAAQgFgDgCgCQgCgDAAgFQAAgGAEgEQAEgDAHgBIASAAIADACIABADIAAAlIgBADQAAABgBAAQAAAAAAAAQgBABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBgAgFgNQgDACAAADQAAAEADACQACACADAAIAMAAIAAgPIgMAAQgDAAgCACg");
	this.shape_97.setTransform(92.1,10.3);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#FFFFFF").s().p("AgIAVQgGgDgCgFQgDgGAAgHQAAgGADgGQADgFAFgDQAGgDAFgBQAFAAAEACIAGACQAAABABAAQAAABAAAAQABABAAAAQAAABAAAAIgBADIgDABIgCAAIgBgBIgCgBIgDgBIgEgBQgEAAgDADQgEACgBAEQgDADAAAEQAAAFADAEQABADAEADQADACAEAAIAFgBIADgBIACgBIACgBIADABIABADQAAAAAAABQAAAAgBABQAAAAAAAAQgBABAAAAQgDACgDABQgEACgFAAQgGAAgFgEg");
	this.shape_98.setTransform(87.4,10.3);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#FFFFFF").s().p("AgCAWIgBgDIAAgiIgNAAIgDgBIgBgDIABgCQAAgBABAAQAAAAABAAQAAgBAAAAQABAAAAAAIAhAAQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACACIgCADIgCABIgNAAIAAAiQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBg");
	this.shape_99.setTransform(82.8,10.3);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAABIABADIAAAbIAYgeIABgBIACgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAmIgBADIgDABIgDgBg");
	this.shape_100.setTransform(77.9,10.3);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#FFFFFF").s().p("AASAdQAAgBgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIAAgIIgfAAIAAAIQAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAABIgDABIgDgBIgBgDIAAgMIABgDIADgBIABAAIACgDIACgFIABgIIAAgOIAAgFQAAAAAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAYAAIADABIABADIAAAjIADAAIADABIABADIAAAMIgBADIgDABIgDgBgAgFgUIgBAPIgCAJIgCAGIAUAAIAAgfIgPAAg");
	this.shape_101.setTransform(72.4,10.9);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_102.setTransform(66.9,10.3);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#FFFFFF").s().p("AgOAYIgDgBIgCgDIAAgnIACgCQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAIARAAQAHABAEADQADADAAAFQAAADgBADQgCADgDACQAEAAACADQACACABAGQgBAFgCACQgCADgEACIgHABgAgKAQIAOAAQADAAACgBQACgCAAgDQAAgEgCgBQgDgCgDAAIgNAAgAgKgDIANAAQAAAAABAAQABAAAAgBQABAAAAAAQABAAAAgBQABAAAAgBQAAAAAAgBQABAAAAgBQAAgBAAAAQAAgBAAgBQAAAAgBgBQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgNAAg");
	this.shape_103.setTransform(61.8,10.3);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#FFFFFF").s().p("AgLAWQgGgEgDgFQgDgGAAgHQAAgGADgGQADgFAGgDQAFgDAGgBQAHABAFADQAFADADAFQAEAGAAAGQAAAHgEAGQgDAFgFAEQgFADgHAAQgGAAgFgDgAgHgNQgDACgCADQgCAEAAAEQAAAFACAEQACAEADACQAEACADAAQAEAAAEgCQADgCACgEQACgEAAgFQAAgEgCgEQgCgDgDgCQgEgDgEAAQgDAAgEADg");
	this.shape_104.setTransform(56.4,10.3);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#FFFFFF").s().p("AgUAgIgCgEIAAg3IACgDQAAAAAAgBQABAAAAAAQAAAAABAAQAAgBABAAQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAIABADIAAACIAEgDIAFgDIAFgBQAGAAAFADQAFADADAGQADAFAAAHQAAAHgDAFQgDAFgFADQgEAEgHAAQgEAAgEgDQgEgCgCgCIAAATIgBAEIgDABIgDgBgAgGgWQgEACgCAEQgBAEAAAEQAAAFABADQACAEAEACQADACADAAQAEAAAEgCQADgDACgDQACgDAAgFQAAgEgCgEQgCgEgDgCQgEgCgEAAQgDAAgDACg");
	this.shape_105.setTransform(50.9,11.2);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#FFFFFF").s().p("AANAXIgCgDIAAgjIgVAAIAAAjIgBADIgDABIgDgBIgCgDIAAgnIACgCQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIAfAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABIABACIAAAnIgBADIgEABIgCgBg");
	this.shape_106.setTransform(45.3,10.3);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#FFFFFF").s().p("AAOAWQgBAAAAAAQAAgBAAAAQgBAAAAgBQAAAAAAgBIAAgNIgJAAIgDABIgDACIgCAFIgDAGIgEADIgCAAIgCABIgDgBIgBgDIABgCIABgBIADgCIACgEIADgEQAAgBAAAAQABgBAAAAQABAAAAgBQABAAAAAAQgFgDgCgCQgCgDAAgFQAAgGAEgEQAEgDAHgBIASAAIADACIABADIAAAlIgBADQAAABgBAAQAAAAgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBgAgFgNQgDACAAADQAAAEADACQACACADAAIAMAAIAAgPIgMAAQgDAAgCACg");
	this.shape_107.setTransform(37.7,10.3);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#FFFFFF").s().p("AANAXIgBgDIAAgbIgYAdIgBABIgCABIgDgBIgBgDIAAgmIABgDQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABABIABADIAAAbIAYgeIABgBIACgBQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIABADIAAAmIgBADIgDABIgDgBg");
	this.shape_108.setTransform(32.6,10.3);

	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#FFFFFF").s().p("AAQAdQAAgBgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAgIIghAAIgCgBIgCgDIAAgnIACgDIACgBIAEABIABADIAAAjIAUAAIAAgjQAAAAABgBQAAAAAAAAQAAgBAAAAQABgBAAAAIADgBIADABIABADIAAAjIADAAQABAAAAAAQAAAAABAAQAAAAAAABQABAAAAAAIABADIAAAMIgBADIgDABIgDgBg");
	this.shape_109.setTransform(27.3,10.9);

	this.shape_110 = new cjs.Shape();
	this.shape_110.graphics.f("#FFFFFF").s().p("AAOAXIgCgBQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgEgGQgBgFgDgCQgCgCgEAAIgFAAIAAAPIgCADQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAAAgBgBIgBgDIAAglIABgDQABgBAAAAQAAAAAAAAQABgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIACADIAAAPIAFAAQAEAAACgCQADgCABgEIADgHIADgDIADgBIACgBIACABIABADIAAACIgBABIgDADIgCAEIgEAGIgFADQADABACADIAEAGIADAEIACADIACABIAAACQAAABAAAAQAAAAAAABQAAAAgBAAQAAABAAAAIgDABIgCgBg");
	this.shape_110.setTransform(22,10.3);

	this.shape_111 = new cjs.Shape();
	this.shape_111.graphics.f("#FFFFFF").s().p("AAVAfIgCgCIgFgOIgbAAIgGAOIgBACIgCABIgDgCIgBgCIAAAAIAAgBIAXg3IACgCIABgBIADABIABACIAXA2IAAABIAAABIgBACIgDACIgCgBgAAKAHIgKgXIgKAXIAUAAg");
	this.shape_111.setTransform(16.5,9.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_111},{t:this.shape_110},{t:this.shape_109},{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol18, new cjs.Rectangle(0,0,273,42.5), null);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbBpQgKgDgHgDQgHgCgEgFQgDgEAAgFQAAgHADgFQAEgEAHAAIAEAAIAFACIAKADQAIACAKAAQASABAKgJQALgJAAgWIAAgCQgHAJgLAFQgLAEgOABQgZgBgPgPQgOgPAAgYIAAhVQAAgIAFgEQAEgFAIgBQAIABAEAFQAFAEAAAIIAABLQABARAIAIQAIAIAOgBQAPABAIgJQAIgJAAgPIAAhLQAAgIAFgEQAFgFAIgBQAHABAFAFQAFAEAAAIIAAB6QAAAbgKAQQgKAPgQAIQgRAGgUAAQgKAAgKgBg");
	this.shape.setTransform(148.2,31.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAyBJQgFgFAAgIIAAhKIghAuIgGAFQgDACgDAAIgHgCQgEgCgDgDIgfgtIAABKQAAAHgFAFQgEAFgIAAQgIAAgEgFQgFgFAAgHIAAh3QAAgIAFgFQAFgGAIAAQAFAAAFADQAFADADAEIAtBAIAuhBQACgEAEgCQAEgDAGAAQAGABAFAFQAFAEAAAHIAAB4QAAAIgFAFQgFAEgIABQgHgBgFgEg");
	this.shape_1.setTransform(129.7,28.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnBHQgSgLgKgSQgLgSAAgYQAAgXALgSQAKgSASgLQASgKAVAAQAWAAASAKQASALAKASQALASAAAXQAAAYgLASQgKASgSALQgSAKgWAAQgVAAgSgKgAgVgqQgKAHgGAKQgGALAAAOQAAAPAGALQAGALAKAGQAKAFALAAQAMAAAKgFQAKgGAGgLQAGgLAAgPQAAgOgGgLQgGgKgKgHQgKgFgMgBQgLABgKAFg");
	this.shape_2.setTransform(110.7,28.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwBOQgIAAgFgFQgEgFAAgHIAAh5QAAgHAEgFQAFgFAIAAIA6AAQAXAAANALQANAKAAARQgBALgEAKQgFAIgIAGQAKAEAIAIQAHAJAAARQAAARgIAKQgJAJgNAEQgMAEgNAAgAgfAvIArAAQAJAAAFgEQAGgEAAgJQgBgJgGgEQgGgFgJABIgpAAgAgfgPIAoAAQAHAAAEgEQADgFABgHQAAgIgFgEQgDgDgIAAIgnAAg");
	this.shape_3.setTransform(93.9,28.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgnBHQgSgLgKgSQgLgSAAgYQAAgXALgSQAKgSASgLQASgKAVAAQAWAAASAKQASALAKASQALASAAAXQAAAYgLASQgKASgSALQgSAKgWAAQgVAAgSgKgAgVgqQgKAHgGAKQgGALAAAOQAAAPAGALQAGALAKAGQAKAFALAAQAMAAAKgFQAKgGAGgLQAGgLAAgPQAAgOgGgLQgGgKgKgHQgKgFgMgBQgLABgKAFg");
	this.shape_4.setTransform(76.2,28.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAmBJQgEgFAAgIIAAgsIhDAAIAAAsQAAAIgEAFQgGAEgHABQgIgBgEgEQgGgFAAgIIAAh3QAAgHAGgFQAEgFAIgBQAHABAGAFQAEAFAAAHIAAAsIBDAAIAAgsQAAgHAEgFQAFgFAIgBQAIABAFAFQAEAFAAAHIAAB3QAAAIgEAFQgFAEgIABQgIgBgFgEg");
	this.shape_5.setTransform(58.4,28.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYARQgIAAgFgFQgEgFgBgHQABgHAEgFQAFgEAIAAIAxAAQAIAAAFAFQAFAEAAAHQAAAIgFAEQgFAFgIAAg");
	this.shape_6.setTransform(43.5,27.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgnBHQgSgLgKgSQgLgSAAgYQAAgXALgSQAKgSASgLQASgKAVAAQAWAAASAKQASALAKASQALASAAAXQAAAYgLASQgKASgSALQgSAKgWAAQgVAAgSgKgAgVgqQgKAHgGAKQgGALAAAOQAAAPAGALQAGALAKAGQAKAFALAAQAMAAAKgFQAKgGAGgLQAGgLAAgPQAAgOgGgLQgGgKgKgHQgKgFgMgBQgLABgKAFg");
	this.shape_7.setTransform(28.5,28.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAlBJQgFgFAAgHIAAhqIg/AAIAABqQAAAHgFAFQgFAFgIAAQgHAAgFgFQgFgFAAgHIAAh5QAAgHAEgFQAFgFAHAAIBlAAQAHAAAFAFQAEAEAAAHIAAB6QAAAHgFAFQgFAFgIAAQgHAAgFgFg");
	this.shape_8.setTransform(10.8,28.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol16, new cjs.Rectangle(0,0,158.9,47.5), null);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgkBGQgRgKgKgSQgJgSgBgWQAAgZALgTQAKgSARgKQARgKASAAQAUAAARALQAQAKAKARQALASAAAVQAAAGgFAFQgGAEgHAAIheAAQACAMAHAIQAHAJAIAEQAKADAJAAQAKAAAGgBIALgEIAHgFIAFgCIAFAAQAGAAAFAEQADAFAAAGIgBAHQgCADgFAEQgHAHgNAEQgOAEgOABQgZgBgSgKgAgYgpQgLAHgDASIBLAAIAAgCQgBgIgFgHQgFgHgJgEQgHgEgKAAQgNAAgLAHg");
	this.shape.setTransform(123.4,28.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLBJQgFgFAAgIIAAhpIgkAAQgHAAgEgFQgFgEAAgHQAAgGAFgFQAEgFAHAAIBpAAQAHAAAFAFQAEAFAAAGQAAAHgEAEQgFAFgHAAIgjAAIAABpQgBAIgEAFQgFAEgIABQgGgBgFgEg");
	this.shape_1.setTransform(107.5,28.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrBOQgHAAgFgEQgFgFAAgHIAAh7QABgHAFgEQAEgFAIAAQAHAAAGAFQAEAEAAAHIAAApIAhAAQAYAAAOANQAOANABAWQAAAPgIALQgGAMgMAGQgLAGgQAAgAgZAwIAeAAQAJgBAGgFQAFgFAAgJQAAgJgFgEQgGgFgJAAIgeAAg");
	this.shape_2.setTransform(93.3,28.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwBOQgIAAgFgFQgEgFAAgHIAAh5QAAgHAEgFQAFgFAIAAIA6AAQAYAAAMALQANAKAAARQAAALgFAKQgFAIgIAGQAKAEAIAIQAHAJAAARQAAARgJAKQgIAJgNAEQgMAEgNAAgAgfAvIArAAQAJAAAFgEQAFgEABgJQgBgJgGgEQgGgFgJABIgpAAgAgfgPIAoAAQAHAAAEgEQADgFABgHQAAgIgFgEQgDgDgIAAIgnAAg");
	this.shape_3.setTransform(77.5,28.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgnBHQgSgLgKgSQgLgSAAgYQAAgXALgSQAKgSASgLQASgKAVAAQAWAAASAKQASALAKASQALASAAAXQAAAYgLASQgKASgSALQgSAKgWAAQgVAAgSgKgAgVgqQgKAHgGAKQgGALAAAOQAAAPAGALQAGALAKAGQAKAFALAAQAMAAAKgFQAKgGAGgLQAGgLAAgPQAAgOgGgLQgGgKgKgHQgKgFgMgBQgLABgKAFg");
	this.shape_4.setTransform(59.8,28.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLBJQgFgFAAgIIAAhpIgkAAQgHAAgEgFQgFgEAAgHQAAgGAFgFQAEgFAHAAIBpAAQAHAAAFAFQAEAFAAAGQAAAHgEAEQgFAFgHAAIgjAAIAABpQgBAIgEAFQgFAEgIABQgGgBgFgEg");
	this.shape_5.setTransform(43.5,28.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnBHQgSgLgKgSQgLgSAAgYQAAgXALgSQAKgSASgLQASgKAVAAQAWAAASAKQASALAKASQALASAAAXQAAAYgLASQgKASgSALQgSAKgWAAQgVAAgSgKgAgVgqQgKAHgGAKQgGALAAAOQAAAPAGALQAGALAKAGQAKAFALAAQAMAAAKgFQAKgGAGgLQAGgLAAgPQAAgOgGgLQgGgKgKgHQgKgFgMgBQgLABgKAFg");
	this.shape_6.setTransform(27.1,28.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag8BgQgGgEAAgIIAAinQAAgHAFgFQAFgGAIAAIBhAAQAIABAFAEQAFAEAAAJQAAAHgFAEQgFAFgIAAIhNAAIAACXQAAAIgFAEQgGAFgIABQgIgBgFgFg");
	this.shape_7.setTransform(11.1,26.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol14, new cjs.Rectangle(0,0,133.8,47.5), null);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhBBwQgGgFAAgKIAAgOIgFAAQgJAAgGgEQgFgGAAgJQAAgIAFgEQAGgGAJAAIAFAAIAAgOIgFAAQgJABgGgGQgFgGAAgIQAAgIAFgFQAGgFAJgBIAFAAIAAhbQAAgKAGgFQAFgGAKAAIBFAAQAXAAASALQARAKAKARQAKARAAAVQAAAWgKARQgKAQgRAKQgSAKgXABIguAAIAAAMIAKAAQAKAAAFAGQAFAEAAAIQAAAJgFAGQgFAEgKAAIgKAAIAAAOQAAAKgGAFQgHAHgJAAQgKAAgGgHgAgbgEIAyAAQAPAAAJgLQAJgKAAgRQAAgRgJgKQgJgKgPAAIgyAAg");
	this.shape.setTransform(153.3,44.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhCCRQgbgVgPglQgOglAAgyQAAgwAOglQAPgmAbgUQAbgVAngBQAoABAbAVQAbAUAPAmQAOAlAAAwQAAAygOAlQgPAlgbAVQgbAVgoAAQgnAAgbgVgAgthSQgRAcAAA2QAAA4ARAbQARAcAcAAQAdAAARgcQARgbAAg4QAAg2gRgcQgRgbgdAAQgcAAgRAbg");
	this.shape_1.setTransform(127.4,40.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag8CeQgIgFAAgPQAAgKAGgIQAHgHALgEQATgEARgMQARgLAOgQQAOgQAIgVQgJAJgNAGQgOAFgQAAQgYAAgXgOQgXgOgOgXQgPgYgBgeQABgeAOgZQAOgXAYgPQAZgOAdAAQAhAAAYATQAYARAOAdQANAcAAAhQAAAQgEAVQgDAWgJAYQgIAYgQAXQgQAXgYATQgZARghALIgGABIgFAAQgLAAgIgGgAgkhgQgPAPAAAZQAAAYAPAQQAOAPAWABQAWgBAPgPQAOgQABgYQgBgZgOgPQgPgQgWgBQgWABgOAQg");
	this.shape_2.setTransform(100,40.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag8CeQgIgFAAgPQAAgKAGgIQAHgHALgEQATgEARgMQARgLAOgQQAOgQAIgVQgJAJgNAGQgOAFgQAAQgYAAgXgOQgXgOgOgXQgPgYgBgeQABgeAOgZQAOgXAYgPQAZgOAdAAQAhAAAYATQAYARAOAdQANAcAAAhQAAAQgEAVQgDAWgJAYQgIAYgQAXQgQAXgYATQgZARghALIgGABIgFAAQgLAAgIgGgAgkhgQgPAPAAAZQAAAYAPAQQAOAPAWABQAWgBAPgPQAOgQABgYQgBgZgOgPQgPgQgWgBQgWABgOAQg");
	this.shape_3.setTransform(75,40.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag4CSQgYgRgNgdQgNgdgBghQAAgPAEgWQADgWAJgYQAJgYAPgXQAQgXAYgSQAZgSAhgKIAGgBIAFgBQALAAAIAFQAIAHABAOQgBAKgGAHQgHAIgLAEQgSAFgSALQgQALgOAQQgOAQgIAVQAJgJANgFQANgGAQgBQAZABAWAOQAXAOAPAXQAOAZABAdQgBAegOAYQgOAZgYAOQgYAOgeAAQghAAgYgSgAgjASQgPAPAAAYQAAAZAPAQQAOAPAWAAQAWAAAPgPQAOgQABgZQgBgYgOgPQgPgRgWAAQgWAAgOARg");
	this.shape_4.setTransform(39.7,40.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhMCkQgMAAgHgIQgGgHAAgMQAAgFACgFQACgFAEgFIBjhrQARgRAKgTQAKgSAAgQQAAgPgHgLQgGgMgMgHQgLgGgMgBQgOABgNAIQgNAJgLAPQgGAHgGACQgFACgFAAQgKgBgIgGQgIgIgBgKQAAgIAGgIQAEgHAJgHQASgSAWgLQAXgKAWgBQAdABAYANQAWAMANAXQALAWABAdQAAAdgQAeQgPAdgYAaIg6A+IBeAAQALAAAIAIQAGAGABAMQgBAKgGAIQgIAGgLABg");
	this.shape_5.setTransform(14.4,40.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol12, new cjs.Rectangle(0,0,166.1,73), null);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AACA6QgFgCgEgGQgFgFAAgMIAAgwIgJAAQgEgBgDgCQgDgDAAgEQAAgFADgCQADgDAEAAIAJAAIAAgMQAAgEADgEQADgCAFgBQADABADACQADAEAAAEIAAAMIANAAQAEAAAEADQACADAAAEQAAAEgCADQgEACgEABIgNAAIAAAvQABAEACACQACACADAAIAEgBIAEgBQADAAACADQACACAAAEQgBADgCADQgDACgDACIgJABIgLAAg");
	this.shape.setTransform(211.1,17.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAXAtQgCgDgBgEIAAgtQAAgKgEgGQgEgFgJAAQgKAAgGAHQgHAIABAMIAAAnQgBAEgDADQgCAEgGAAQgEAAgDgEQgDgDAAgEIAAhJQAAgFADgDQADgDAEAAQAGAAACADQADADABAEIAAACQADgDAEgEQAEgDAGgCQAEgCAIAAQAPAAAJAKQAHAKABAVIAAAtQAAAEgDADQgEAEgEAAQgFAAgDgEg");
	this.shape_1.setTransform(202.4,18.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHA9QgDgDAAgEIAAhJQAAgFADgDQADgDAEgBQAFABADADQADADAAAFIAABJQAAAEgDADQgDAEgFAAQgEAAgDgEgAgIgsQgCgCAAgFIAAgEQAAgFACgCQADgCAFAAQAGAAADACQACACAAAFIAAAEQAAAFgCACQgDACgGAAQgFAAgDgCg");
	this.shape_2.setTransform(194.6,16.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgYArQgLgGgGgLQgHgLAAgPQAAgOAHgLQAGgMALgGQALgGANAAQAOAAALAGQALAGAGAMQAHALAAAOQAAAPgHALQgGALgLAGQgLAHgOAAQgNAAgLgHgAgNgaQgGAEgDAHQgFAHAAAIQAAAJAFAHQADAGAGAEQAGAEAHAAQAHAAAHgEQAGgEADgGQAEgHAAgJQAAgIgEgHQgDgHgGgEQgHgDgHAAQgHAAgGADg");
	this.shape_3.setTransform(186.7,18.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgrBAQgDgDAAgFIAAhuQAAgEADgDQADgDAFAAQAEAAADADQAEADAAAEIAAABQACgDAFgDQAEgDAFgCQAGgCAFAAQANAAAJAGQAKAGAGALQAGAMAAAOQAAAPgGALQgGALgKAGQgJAHgNAAQgIgBgIgDQgHgDgEgFIAAAjQAAAFgEADQgDADgEAAQgFAAgDgDgAgNgrQgGAFgDAGQgEAHABAIQgBAKAEAGQADAGAGAEQAGAEAHAAQAIAAAGgEQAGgEADgGQAEgGAAgKQAAgIgEgHQgDgGgGgFQgGgDgIAAQgHAAgGADg");
	this.shape_4.setTransform(175.6,20.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AACA6QgFgCgFgGQgEgFAAgMIAAgwIgIAAQgFgBgCgCQgDgDAAgEQAAgFADgCQACgDAFAAIAIAAIAAgMQAAgEADgEQADgCAFgBQADABAEACQACAEAAAEIAAAMIANAAQAEAAADADQADADABAEQgBAEgDADQgDACgEABIgNAAIAAAvQABAEABACQACACAEAAIAEgBIAEgBQACAAACADQACACAAAEQAAADgCADQgDACgEACIgHABIgMAAg");
	this.shape_5.setTransform(166.1,17.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYArQgLgGgGgLQgHgLAAgPQAAgOAHgLQAGgMALgGQALgGANAAQANAAAMAGQALAGAGAMQAHALAAAOQAAAPgHALQgGALgLAGQgMAHgNAAQgNAAgLgHgAgNgaQgGAEgDAHQgEAHAAAIQAAAJAEAHQADAGAGAEQAHAEAGAAQAIAAAGgEQAGgEADgGQAEgHABgJQgBgIgEgHQgDgHgGgEQgGgDgIAAQgGAAgHADg");
	this.shape_6.setTransform(157.2,18.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAgA8QgDgDAAgFIAAgqIg5AAIAAAqQAAAFgDADQgDADgFAAQgFAAgDgDQgDgDAAgFIAAhnQAAgFADgDQADgDAFAAQAFAAADADQADADAAAFIAAApIA5AAIAAgpQAAgFADgDQAEgDAEAAQAFAAADADQADADAAAFIAABnQAAAFgDADQgDADgFAAQgFAAgDgDg");
	this.shape_7.setTransform(145,17.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgGBSQgEgEAAgEIAAgYQgOAAgMgHQgLgGgHgKQgGgMAAgOQAAgOAGgLQAHgMALgGQAMgGAOgBIAAgYQAAgEAEgDQADgEADAAQAEAAADAEQADADABAEIAAAZQAOAAALAHQAMAFAHAMQAGALAAAOQABAPgIALQgGAKgMAHQgLAGgOAAIAAAYQgBAEgDAEQgDACgEABQgDgBgDgCgAALAfQAIAAAHgEQAGgEAEgHQAFgHAAgIQAAgJgFgGQgEgIgGgDQgHgEgIAAgAgZgZQgGADgFAIQgDAGAAAJQAAAIADAHQAFAHAHAEQAGAEAIAAIAAg8QgIAAgHAEg");
	this.shape_8.setTransform(127.3,18.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgZArQgKgGgGgMQgFgLgBgOQABgNAGgMQAFgLALgHQAKgGALAAQAJAAAHAEQAJAEAEAGIAAgCQAAgEADgDQADgDAFAAQAFAAADACQADAEAAAEIAABKQAAAFgDADQgDADgFAAQgFAAgDgDQgDgDAAgFIAAgDQgEAHgJAEQgHAFgKAAQgMAAgJgHgAgMgaQgGAFgEAGQgCAHAAAIQAAAIACAIQAEAGAGAEQAFAEAIAAQAHAAAGgEQAHgEACgGQAEgIAAgIQAAgIgEgHQgCgGgHgFQgGgDgHAAQgIAAgFADg");
	this.shape_9.setTransform(114.4,18.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAcAwIgGgDQgDgCgDgFQgEgEgDgIQgEgIgFgEQgFgEgFAAIgKAAIAAAbQAAAFgDADQgDADgFAAQgFAAgDgDQgDgDAAgFIAAhJQAAgFADgDQADgDAFAAQAFAAADADQADADAAAFIAAAcIAJAAQAGAAAFgEQAEgEAEgIIAGgMQAEgFACgCQADgDADAAIAFgBQAEAAADACQADADAAADIgBAFIgEAEIgEAEIgEAIQgEAHgFAFQgEAFgFABQAFADAFAEQAEAEAEAIIAFAHIAFAFIADADQACACAAADQgBAEgDADQgCACgFAAIgEAAg");
	this.shape_10.setTransform(104.3,18.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgzAwQgFABgCgDQgDgDAAgEIAAhNQAAgEADgCQADgEAEAAQAGAAACAEQADACAAAFIAABDIAeAAIAAhEQAAgEADgCQADgEAEAAQAFAAADAEQADACAAAFIAABDIAdAAIAAhEQABgEADgCQACgEAGAAQAEAAADAEQADACAAAFIAABLQAAAFgCADQgDADgFgBg");
	this.shape_11.setTransform(91.3,18.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAZA8QgCgDgBgEIAAgwIgtA3IgDACIgGABQgEAAgDgDQgDgDAAgEIAAhLQAAgEADgDQADgDAEAAQAFAAADADQADADAAAEIAAAvIAtg1IAEgDIAEgBQAFAAADADQADADAAAEIAABLQAAAEgDADQgCADgGAAQgEAAgDgDgAgSgoQgHgEgEgIQgBgFABgCQACgDADAAQAEAAADACIAEAEQADADADABQACABAFAAQADAAADgBQADgBACgDIAFgEQACgCAEAAQAEAAACADQABACgBAEQgEAJgHAEQgIAEgJAAQgKAAgIgEg");
	this.shape_12.setTransform(74,17.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYArQgLgGgHgLQgGgLAAgPQAAgOAGgLQAHgMALgGQALgGANAAQANAAAMAGQALAGAHAMQAGALAAAOQAAAPgGALQgHALgLAGQgMAHgNAAQgNAAgLgHgAgNgaQgGAEgEAHQgDAHAAAIQAAAJADAHQAEAGAGAEQAGAEAHAAQAHAAAHgEQAGgEADgGQAEgHABgJQgBgIgEgHQgDgHgGgEQgHgDgHAAQgHAAgGADg");
	this.shape_13.setTransform(62.9,18.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeAwQgEAAgDgDQgDgCAAgFIAAhLQAAgEADgDQADgDAEAAIAkAAQAPAAAHAHQAIAGAAAKQAAAIgDAFQgCAFgGAEQAGACAFAFQAFAGAAAKQAAALgGAGQgFAGgHACQgIACgIAAgAgTAdIAaAAQAGAAADgCQADgDAAgFQAAgGgEgDQgDgCgGAAIgZAAgAgTgJIAZAAQADAAADgDQACgCABgFQgBgFgCgCQgCgCgFAAIgYAAg");
	this.shape_14.setTransform(52.5,18.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgYArQgLgGgGgLQgHgLAAgPQAAgOAHgLQAGgMALgGQALgGANAAQANAAAMAGQALAGAGAMQAHALAAAOQAAAPgHALQgGALgLAGQgMAHgNAAQgNAAgLgHgAgNgaQgGAEgEAHQgDAHAAAIQAAAJADAHQAEAGAGAEQAHAEAGAAQAIAAAGgEQAGgEADgGQAEgHABgJQgBgIgEgHQgDgHgGgEQgGgDgIAAQgGAAgHADg");
	this.shape_15.setTransform(41.5,18.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAZAvQgCgBgCgDIgVgbIgVAbIgDAEIgFABQgEAAgDgDQgDgDgBgEIABgDIACgDIAZgfIgagfIgCgEIAAgDQAAgEADgEQADgCAFAAQABAAAAAAQABAAAAAAQABAAAAAAQABABABAAIADADIAWAcIAUgcQAEgEAFAAQAFAAACACQADAEAAAEIgBADIgBAEIgZAdIAaAgIABADIABADQAAAFgDADQgDAEgFAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBgBgBAAg");
	this.shape_16.setTransform(31.2,18.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgQBBQgHgBgEgCQgEgCgDgDQgCgCAAgDQAAgFADgDQACgDAEAAIADABIADABIAGACIALACQALAAAGgGQAHgFAAgOIAAgCQgFAGgGADQgHADgJAAQgPAAgJgJQgJgKAAgOIAAg1QAAgFADgDQADgDAFAAQAFAAACADQADADABAFIAAAuQAAALAFAFQAFAEAIAAQAJAAAFgFQAFgFABgKIAAguQAAgFADgDQADgDAEAAQAFAAADADQADADAAAFIAABLQAAARgGAKQgGAKgKAEQgLAEgLAAIgNgBg");
	this.shape_17.setTransform(21.1,20.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAtBMQgEgDAAgFIAAgVIhRAAIAAAVQAAAFgEADQgDADgFAAQgFAAgDgDQgDgDgBgFIAAgfQABgFADgDQADgDAEAAIAEAAIAEgHQADgFABgIIACgXIABgnIAAgLQAAgFADgDQADgDAFAAIBAAAQAFAAADACQADADAAAFIAABeIAGAAQAEAAADADQAEADAAAEIAAAgQAAAFgEADQgDADgFAAQgFAAgDgDgAgPg4QAAAYgBAQQgBAQgDAKQgCAKgDAGIAxAAIAAhUIgnAAg");
	this.shape_18.setTransform(8.8,18.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol10, new cjs.Rectangle(0,0,216.7,31), null);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Bitmap10();
	this.instance.parent = this;
	this.instance.setTransform(0,600,1,1,-90);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol8, new cjs.Rectangle(0,0,337,600), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#080503").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,300,600), null);


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Egm+AMHIAA4OMBN9AAAIAAYOg");
	mask.setTransform(249.5,77.6);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjNDTQhFhHAAiMQABkZERAAQESAAAAEZQAAEakSAAQiIAAhFhHgAhriDQghAoAABbQAABeAgAnQAgAoBMAAQBMAAAggoQAhgoAAhdQgBhcgggoQgggohMAAQhLAAggApg");
	this.shape.setTransform(133.2,88);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ACkFjQgRgPAAgbIAAj/IkkAAIAAD/QAAAdgXAQQgTAMgcAAQgfAAgSgPQgRgPAAgbIAApyQAAgcAWgQQAUgMAcAAQAfAAARAPQASAOAAAbIAAD4IEkAAIAAj4QgBgcAXgQQATgMAcAAQAfAAASAPQASAPAAAaIAAJyQAAAdgYAQQgSAMgcAAQgfAAgSgPg");
	this.shape_1.setTransform(67.3,78);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AjuFwQgVgPAAgeIAApHQAAhWBSgSQBDgPBcAAQEWAAAAEUQAABOgeA6QgdA4g1AhQglAWgkAJQgpALg6AAQgzAAgwgLIAACqQAAAegVAPQgTAMgdAAQgbAAgTgMgAh7kDIAAEzQAkAJA6AAQBWAAAigmQAggkAAhhQAAhUgjgjQgjgjhQAAQg2ABgqAIg");
	this.shape_2.setTransform(238.3,99.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag1A3QgXgWAAghQAAgfAXgXQAWgXAfAAQAgAAAXAXQAWAWAAAgQAAAhgWAWQgXAXggAAQgfAAgWgXg");
	this.shape_3.setTransform(343.6,46.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AguECQgWgQAAgeIAAmmQAAgeAWgQQATgNAbgBQAdABASANQAWAQAAAeIAAGmQAAAegWAQQgSAMgdAAQgbAAgTgMg");
	this.shape_4.setTransform(343.6,88);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ACID/QgSgOAAgaIAAkKQAAg9gRgUQgUgWg9ABIgnAAQg9gBgTAWQgSAUAAA9IAAEKQAAAagSAOQgTAPggAAQgfAAgSgPQgTgOABgaIAAkTQAAhuA1gyQA0gxB1AAIA+AAQB2AAA0AxQA1AyAABuIAAETQABAagTAOQgRAPggAAQghAAgSgPg");
	this.shape_5.setTransform(387.9,88);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAMFrQhYAAgvgoQgugpAAhOIAAn+QAAgcAXgQQAUgMAcAAQAfAAARAPQASAPAAAaIAACLICVAAQAVAAAMAQQAKAPAAAVQAAAVgKAOQgMARgVAAIiVAAIAAD2QAAAyAXAPQARALA0AAIBDAAQAVAAAMARQAKAOAAAVQAAAVgKAPQgMAQgVAAg");
	this.shape_6.setTransform(187.7,78.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AALFrQhXAAgvgoQgtgpgBhOIAAn+QAAgcAYgQQASgMAdAAQAeAAASAPQARAPAAAaIAACLICWAAQAVAAAMAQQAKAPAAAVQAAAVgKAOQgMARgVAAIiWAAIAAD2QABAyAXAPQARALA0AAIBCAAQAWAAAMARQAJAOABAVQgBAVgJAPQgMAQgWAAg");
	this.shape_7.setTransform(441.9,78.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AjMDTQhGhHAAiMQAAiLBGhHQBFhHCIAAQESAAgBEZQAACMhEBHQhFBHiIAAQiIAAhFhHgAhriDQggAogBBbQAABeAhAnQAfAoBMAAQBLAAAhgoQAhgogBhdQAAhcgfgoQghgohMAAQhKAAghApg");
	this.shape_8.setTransform(299.1,88);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(39.1,38.4,419.8,98.7), null);


(lib.Schermata20200220alle161732 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EAATAp2Mgg1gANQgBABgIgGQgIgFgCABQgBABAFjNQAEjNgBABQgCABj3gBIj5AAQgCABDlk/QDgk5ADgGQABABA3AFIA4AGIAAAAIAAAAIAsguQgCABAGgOQAGgNgBABQgBABhLACIhNADQgBAAgC7cQgB7egCABQgBABAEgJQAFgIgCAAQgBABABlmQAClngCgCUAACAABAjCAAAUAjGAAAgABAACUgABAABgACAhCMgADAhBQgBABhHgEIhHgDQgBABgNABIgOABIgFASIgFARIAAAOQABANgBABIgXgNQgWgNgBABQgBABAQAfQARAggBABQC2gNgCABIB+EtQB/EtgBABQgBABjrgDIjtgBQgBABABDlQABDmgBAAIgKAAQiHAA+kgMgEghOgqBIAAAAIAAAAg");
	var mask_graphics_1 = new cjs.Graphics().p("EggqAhLIACgEQgBABhLACIgsABIghAAQgBgygC6pQgB7dgCABQgBABAEgJQAFgIgCAAQgBABABlmQAClngCgCUAACAABAjCAAAUAjGAAAgABAACUgABAABgACAhCMgADAhBQgBABhHgEIhHgDQgBABgNABIgOABIgFARgEgjBghKIAAAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:259.9,y:269.5}).wait(1).to({graphics:mask_graphics_1,x:271.4,y:212.8}).wait(1));

	// Layer_1
	this.instance = new lib.oven();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.867,0.867);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.6,0.5,518.7,538.1);


(lib.Layer4_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AyxPvQACgBgCgOQgBgPABgBQACgBAAgIQAAgHABgCQACgBA+AEQA+AFABgCQABgBgCgQQgDgQABgBQACgBhAAEQg/AEABgCQACgBgDuyQgDuxABAAQABAAAEgaQACgZACACMAlSAAAQABAAgBASQgBATABAAQABABAAASQABATABAAQABAAABOqQABOaACAPIgOACQgQACABgBQADgDgRAJIAAAAIAAAAQACgBAGAKQAHAKACgCQABgBAMAIQALAJACgCQABgBgEAKIgDAJQgVgByZAEIxVADIhagBg");
	mask.setTransform(120.8,101.3);

	// Layer_1
	this.instance = new lib.Layer4();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Layer4_1, new cjs.Rectangle(0.6,0.6,240.4,201.5), null);


(lib.Layer3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AylOjIgCgRIAFgUIgPgoIhL6rIAMgFIBigCIBIhGICoAFIAPAPIcsgDIANgKIC+gCIA0A+IBiADIgxbBIgbAMIAWAcIAFAWIpcAAI8WAAgAz8tVIAAAAIAAAAg");
	mask.setTransform(127.3,93.1);

	// Layer_1
	this.instance = new lib.Layer31();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Layer3, new cjs.Rectangle(0,0,255.1,186), null);


(lib.Layer2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AybLHIgDgWIASgPIgNgZIiRzhIBvgFIAAAAIAAAAIA5hiIA8ADIAMgUICHAAIAQAeIdhAAIAKgZIBwgDIAHAUIBJgHIA+BhIBkAFIhHTkIgUAMIAXArIgRAFMglhAAMIAAAAIgPgKgAPIrLIAAAAIAAAAg");
	mask.setTransform(132.6,72.3);

	// Layer_1
	this.instance = new lib.Layer21111();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Layer2, new cjs.Rectangle(0.3,0.2,264.5,143.9), null);


(lib.Layer1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AyTHGIgEgUIAIgNIAFgRIjIrNIBpAAIAAAAIAAAAIA5h6IBGAAIANgXICHADIAUARIeLAFIAKgWICMACIAKASIA8AAIA/B4IBvAFIhzLAIgZAZIAXAFIAHAbIgMAIIgRAAMglbgAFgAyTHGIAAAAIAAAAIAAAAg");
	mask.setTransform(137.4,46.1);

	// Layer_1
	this.instance = new lib.Layer11();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Layer1, new cjs.Rectangle(1.1,0.2,272.7,91.8), null);


(lib.hotpoint_verdure_forno_c_cmyk = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Bitmap9();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.hotpoint_verdure_forno_c_cmyk, new cjs.Rectangle(0,0,363,343), null);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol1();
	this.instance.parent = this;
	this.instance.setTransform(150,300,1,1,0,0,0,150,300);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},11).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol16();
	this.instance.parent = this;
	this.instance.setTransform(79.5,86.6,1,1,0,0,0,79.5,23.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:30},7,cjs.Ease.get(1)).to({y:23.8},17,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,62.8,158.9,47.5);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol14();
	this.instance.parent = this;
	this.instance.setTransform(66.9,109.1,1,1,0,0,0,66.9,23.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:33.1,alpha:1},7,cjs.Ease.get(1)).to({y:23.8},16,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,85.3,133.8,47.5);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol12();
	this.instance.parent = this;
	this.instance.setTransform(83,78.8,1,1,0,0,0,83,36.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:43.6,alpha:1},6,cjs.Ease.get(1)).to({y:36.5},13,cjs.Ease.get(1)).wait(46).to({x:-127.3},8,cjs.Ease.get(-1)).wait(38));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,42.3,166.1,73);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol10();
	this.instance.parent = this;
	this.instance.setTransform(108.4,43.7,1,1,0,0,0,108.4,15.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:19.7,alpha:1},6,cjs.Ease.get(1)).to({y:15.5},14,cjs.Ease.get(1)).wait(54).to({x:337.9,alpha:0},8,cjs.Ease.get(-1)).wait(29));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,28.2,216.7,31);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol8();
	this.instance.parent = this;
	this.instance.setTransform(168.5,300,1,1,0,0,0,168.5,300);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},12).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,337,600);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// по-новому
	this.instance = new lib.Symbol17("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(79.5,56.4,1,1,0,0,0,79.5,23.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(8).to({_off:false},0).wait(92));

	// Готовьте
	this.instance_1 = new lib.Symbol15("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(79.5,23.8,1,1,0,0,0,66.9,23.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(12.6,85.3,133.8,47.5);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 26 990₽
	this.instance = new lib.Symbol13("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(110.3,49.7,1,1,0,0,0,83,36.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).wait(76));

	// Духовой шкаф Hotpoint
	this.instance_1 = new lib.Symbol11("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(108.4,15.5,1,1,0,0,0,108.4,15.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(85));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,28.2,216.7,31);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.ClipGroup();
	this.instance.parent = this;
	this.instance.setTransform(249.5,77.5,1,1,0,0,0,249.5,77.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2B2B2A").s().p("Egm+AMHIAA4OMBN9AAAIAAYOg");
	this.shape.setTransform(249.5,77.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,0,499,155.1), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A3LZUQhyAAhRhRQhRhRAAhyMAAAgnzQAAhyBRhRQBRhRByAAMAvJAAAQByAABRBRQBRBRAAByMAAAAnzQAAByhRBRQhRBRhyAAg");
	mask.setTransform(181,162);

	// Layer_2
	this.instance = new lib.hotpoint_verdure_forno_c_cmyk();
	this.instance.parent = this;
	this.instance.setTransform(181.5,171.5,1,1,0,0,0,181.5,171.5);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(5,14.1,357,310), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_11 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_92 = new cjs.Graphics().p("Ar6htIXvAIIAGDQI3SADg");
	var mask_graphics_94 = new cjs.Graphics().p("AsWipIYtAAIggFQI3RADg");
	var mask_graphics_96 = new cjs.Graphics().p("ArEE2IhDprIYPAHIglJkg");
	var mask_graphics_98 = new cjs.Graphics().p("AsLllIYXAFIglLBI2xAFg");
	var mask_graphics_100 = new cjs.Graphics().p("ArLHeIgmu+IXjAAIgXPBg");
	var mask_graphics_102 = new cjs.Graphics().p("ArOICIgqwGIXxAAIggQJg");
	var mask_graphics_104 = new cjs.Graphics().p("ArLoIIWcgCIgHQTI2aACg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(92).to({graphics:mask_graphics_92,x:222.5,y:300.2}).wait(2).to({graphics:mask_graphics_94,x:222.8,y:294.2}).wait(2).to({graphics:mask_graphics_96,x:223.1,y:273.6}).wait(2).to({graphics:mask_graphics_98,x:223.7,y:267.4}).wait(2).to({graphics:mask_graphics_100,x:224.8,y:248.3}).wait(2).to({graphics:mask_graphics_102,x:225.1,y:244.7}).wait(2).to({graphics:mask_graphics_104,x:225.3,y:239.3}).wait(94));

	// Layer_10
	this.instance = new lib.Symbol2();
	this.instance.parent = this;
	this.instance.setTransform(223.3,239.3,0.461,0.461,0,0,0,181.6,171.6);
	this.instance.alpha = 0.141;
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(92).to({_off:false},0).wait(106));

	// Layer 4
	this.instance_1 = new lib.Layer4_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(224.3,242.9,0.865,0.865,0,0,0,120.5,101);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(104).to({_off:false},0).wait(94));

	// Layer 3
	this.instance_2 = new lib.Layer3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(223.9,249,0.865,0.865,0,0,0,128,93);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(100).to({_off:false},0).wait(2).to({regY:93.1,scaleY:0.91,y:244.8},0).to({_off:true},2).wait(94));

	// Layer 2
	this.instance_3 = new lib.Layer2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(222.2,267.7,0.865,0.865,0,0,0,133,72);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(96).to({_off:false},0).wait(2).to({regX:133.1,regY:72.1,scaleY:0.97,x:222.3,y:260.3},0).to({_off:true},2).wait(98));

	// Layer 1
	this.instance_4 = new lib.Layer1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(220.5,290.2,0.865,0.865,0,0,0,137.1,46.1);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(92).to({_off:false},0).wait(2).to({scaleY:1.11,y:279},0).to({_off:true},2).wait(102));

	// Symbol 2
	this.instance_5 = new lib.Symbol2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(222.2,202.5,0.928,0.928,0,0,0,181.5,171.6);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({alpha:1},17).wait(20).to({regX:181.6,scaleX:0.46,scaleY:0.46,x:222.8,y:239.3},32,cjs.Ease.get(1)).wait(129));

	// Schermata 2020-02-20 alle 16.17.32
	this.instance_6 = new lib.Schermata20200220alle161732("single",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(214.3,215.9,0.928,0.928,0,0,0,259.9,269);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(37).to({startPosition:0},0).to({regX:260,regY:269.1,scaleX:0.46,scaleY:0.46,x:218.8,y:246,alpha:1},32,cjs.Ease.get(1)).wait(23).to({startPosition:1},0).wait(106));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.4,-33.4,481.4,499.4);


// stage content:
(lib._300x600_duhovoy_shkaf = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_8
	this.instance = new lib.Symbol18();
	this.instance.parent = this;
	this.instance.setTransform(150,557.8,1.073,1.073,0,0,0,136.5,22.3);

	this.instance_1 = new lib.Symbol4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(223.9,34.8,0.249,0.249,0,0,0,249.3,77.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(225));

	// Layer_10
	this.instance_2 = new lib.Symbol19("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(150,300,1,1,0,0,0,150,300);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(213).to({_off:false},0).wait(12));

	// Layer 4
	this.instance_3 = new lib.Symbol3("synched",1,false);
	this.instance_3.parent = this;
	this.instance_3.setTransform(136,340.7,0.998,0.998,0,0,0,208.3,216.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(225));

	// Layer_6
	this.instance_4 = new lib.Symbol6("synched",0,false);
	this.instance_4.parent = this;
	this.instance_4.setTransform(150.1,155.4,1.289,1.289,0,0,0,79.5,38.1);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(145).to({_off:false},0).wait(80));

	// Layer 1
	this.instance_5 = new lib.Symbol5("synched",0,false);
	this.instance_5.parent = this;
	this.instance_5.setTransform(150.1,167.9,1.203,1.203,0,0,0,108.4,44.6);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(67).to({_off:false},0).wait(158));

	// Layer_5
	this.instance_6 = new lib.Symbol9("synched",0,false);
	this.instance_6.parent = this;
	this.instance_6.setTransform(168.5,300,1,1,0,0,0,168.5,300);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(40).to({_off:false},0).wait(185));

	// Layer_1
	this.instance_7 = new lib.Symbol1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(225));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(51.8,282.9,579.2,617.1);
// library properties:
lib.properties = {
	id: '54CC0916A91D1546A5D02C9DAC043D5E',
	width: 300,
	height: 600,
	fps: 25,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"300x600_duhovoy_shkaf_atlas_.jpg", id:"300x600_duhovoy_shkaf_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['54CC0916A91D1546A5D02C9DAC043D5E'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;